name: app1-frontend-build

on:
  push:
    branches: [main]
    paths:
      - "apps/app1/frontend/**"
      - ".github/workflows/app1-frontend.yaml"
      - ".github/workflows/build-image.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  image:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/build-image.yaml
    with:
      name: app1-frontend
      context: apps/app1/frontend
      manifest: app-deployments/app1/frontend/deployment.yaml
      
